document.addEventListener('DOMContentLoaded', () => {
    // Inputs
    const ctrlFontSize = document.getElementById('ctrl-font-size');
    const ctrlBgColor = document.getElementById('ctrl-bg-color');
    const ctrlBgOpacity = document.getElementById('ctrl-bg-opacity');
    const ctrlTextColor = document.getElementById('ctrl-text-color');
    const ctrlRadius = document.getElementById('ctrl-radius');
    const ctrlSpacing = document.getElementById('ctrl-spacing');
    const ctrlOutline = document.getElementById('ctrl-outline');
    
    // Outputs
    const chatPreviewBox = document.getElementById('chat-preview');
    const cssOutput = document.getElementById('css-output');
    const generateBtn = document.getElementById('generate-btn');

    function hexToRgba(hex, opacity) {
        let r = parseInt(hex.slice(1, 3), 16),
            g = parseInt(hex.slice(3, 5), 16),
            b = parseInt(hex.slice(5, 7), 16);
        return `rgba(${r}, ${g}, ${b}, ${opacity / 100})`;
    }

    function updatePreview() {
        const fontSize = ctrlFontSize.value + 'px';
        const bgColor = hexToRgba(ctrlBgColor.value, ctrlBgOpacity.value);
        const textColor = ctrlTextColor.value;
        const radius = ctrlRadius.value + 'px';
        const spacing = ctrlSpacing.value + 'px';
        const outline = ctrlOutline.checked ? '1px 1px 2px black, -1px -1px 2px black' : 'none';

        // Apply to preview container
        chatPreviewBox.style.gap = spacing;

        const chatLines = document.querySelectorAll('.chat-line');
        chatLines.forEach(line => {
            line.style.fontSize = fontSize;
            line.style.backgroundColor = bgColor;
            line.style.color = textColor;
            line.style.borderRadius = radius;
            line.style.textShadow = outline;
        });
    }

    function generateCSS() {
        const fontSize = ctrlFontSize.value + 'px';
        const bgColor = hexToRgba(ctrlBgColor.value, ctrlBgOpacity.value);
        const textColor = ctrlTextColor.value;
        const radius = ctrlRadius.value + 'px';
        const spacing = ctrlSpacing.value + 'px';
        const outline = ctrlOutline.checked ? '1px 1px 2px black, -1px -1px 2px black' : 'none';

        // Base CSS targeted for standard Streamlabs/StreamElements chat widgets
        const cssTemplate = `/* Generated by obsmaskgenerator.com */
body {
    background: transparent !important;
}

#log > div {
    font-size: ${fontSize} !important;
    color: ${textColor} !important;
    background-color: ${bgColor} !important;
    border-radius: ${radius} !important;
    margin-bottom: ${spacing} !important;
    padding: 8px 12px !important;
    text-shadow: ${outline} !important;
}

/* StreamElements specific wrapper */
.chat-box {
    gap: ${spacing};
}
.chat-line {
    font-size: ${fontSize} !important;
    color: ${textColor} !important;
    background-color: ${bgColor} !important;
    border-radius: ${radius} !important;
    margin-bottom: ${spacing} !important;
    text-shadow: ${outline} !important;
}
`;
        cssOutput.value = cssTemplate;
        cssOutput.select();
        document.execCommand('copy');
        generateBtn.innerText = "Copied to Clipboard!";
        setTimeout(() => { generateBtn.innerText = "Generate CSS"; }, 2000);
    }

    // Event listeners
    [ctrlFontSize, ctrlBgColor, ctrlBgOpacity, ctrlTextColor, ctrlRadius, ctrlSpacing, ctrlOutline].forEach(el => {
        el.addEventListener('input', updatePreview);
    });

    generateBtn.addEventListener('click', generateCSS);

    // Init
    updatePreview();
});
