// OBS Noise Gate Calculator - Script

document.addEventListener('DOMContentLoaded', () => {
    const noiseFloorSlider = document.getElementById('noise-floor');
    const noiseFloorValue = document.getElementById('noise-floor-value');
    const sensitivitySelect = document.getElementById('sensitivity');
    const calculateBtn = document.getElementById('calculate-btn');
    const copyBtn = document.getElementById('copy-btn');

    // Result elements
    const closeThreshold = document.getElementById('close-threshold');
    const openThreshold = document.getElementById('open-threshold');
    const attackTime = document.getElementById('attack-time');
    const holdTime = document.getElementById('hold-time');
    const releaseTime = document.getElementById('release-time');

    // Settings based on sensitivity
    const sensitivitySettings = {
        tight: {
            closeOffset: -3,   // dB below noise floor
            openOffset: 8,     // dB above noise floor
            attack: 5,
            hold: 75,
            release: 50
        },
        balanced: {
            closeOffset: -5,
            openOffset: 5,
            attack: 6,
            hold: 100,
            release: 60
        },
        loose: {
            closeOffset: -8,
            openOffset: 3,
            attack: 8,
            hold: 150,
            release: 100
        }
    };

    // Update slider value display
    noiseFloorSlider.addEventListener('input', () => {
        noiseFloorValue.textContent = `${noiseFloorSlider.value} dB`;
    });

    // Calculate settings
    function calculateSettings() {
        const noiseFloor = parseInt(noiseFloorSlider.value);
        const sensitivity = sensitivitySelect.value;
        const settings = sensitivitySettings[sensitivity];

        const close = noiseFloor + settings.closeOffset;
        const open = noiseFloor - settings.openOffset;

        closeThreshold.textContent = `${close} dB`;
        openThreshold.textContent = `${open} dB`;
        attackTime.textContent = `${settings.attack} ms`;
        holdTime.textContent = `${settings.hold} ms`;
        releaseTime.textContent = `${settings.release} ms`;

        // Add animation
        document.querySelectorAll('.result-card').forEach((card, i) => {
            card.style.animation = 'none';
            card.offsetHeight; // Trigger reflow
            card.style.animation = `fadeIn 0.3s ease ${i * 0.05}s both`;
        });
    }

    // Initial calculation
    calculateSettings();

    // Calculate on button click
    calculateBtn.addEventListener('click', calculateSettings);

    // Also calculate on input change for instant feedback
    noiseFloorSlider.addEventListener('input', calculateSettings);
    sensitivitySelect.addEventListener('change', calculateSettings);

    // Copy settings to clipboard
    copyBtn.addEventListener('click', () => {
        const noiseFloor = parseInt(noiseFloorSlider.value);
        const sensitivity = sensitivitySelect.value;
        const settings = sensitivitySettings[sensitivity];

        const close = noiseFloor + settings.closeOffset;
        const open = noiseFloor - settings.openOffset;

        const settingsText = `OBS Noise Gate Settings:
Close Threshold: ${close} dB
Open Threshold: ${open} dB
Attack Time: ${settings.attack} ms
Hold Time: ${settings.hold} ms
Release Time: ${settings.release} ms

Generated by: obsmaskgenerator.com/noise-gate-calculator/`;

        navigator.clipboard.writeText(settingsText).then(() => {
            const originalText = copyBtn.innerHTML;
            copyBtn.innerHTML = `
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <polyline points="20 6 9 17 4 12"/>
                </svg>
                Copied!
            `;
            copyBtn.style.borderColor = '#10b981';
            copyBtn.style.color = '#10b981';

            setTimeout(() => {
                copyBtn.innerHTML = originalText;
                copyBtn.style.borderColor = '';
                copyBtn.style.color = '';
            }, 2000);
        });
    });
});

// Add CSS animation
const style = document.createElement('style');
style.textContent = `
    @keyframes fadeIn {
        from {
            opacity: 0;
            transform: translateY(10px);
        }
        to {
            opacity: 1;
            transform: translateY(0);
        }
    }
`;
document.head.appendChild(style);
