/**
 * OBS Settings Generator - Logic
 */

document.addEventListener('DOMContentLoaded', () => {
    const generateBtn = document.getElementById('generate-btn');
    const copyBtn = document.getElementById('copy-btn');

    // Generate settings on button click
    generateBtn.addEventListener('click', generateSettings);

    // Copy settings to clipboard
    copyBtn.addEventListener('click', copySettings);

    // Generate on page load with defaults
    generateSettings();
});

function generateSettings() {
    const gpu = document.getElementById('gpu-type').value;
    const uploadSpeed = parseInt(document.getElementById('upload-speed').value);
    const platform = document.getElementById('platform').value;
    const contentType = document.getElementById('content-type').value;
    const qualityPriority = document.getElementById('quality-priority').value;

    // Determine encoder based on GPU
    let encoder;
    switch (gpu) {
        case 'nvidia':
            encoder = 'NVENC H.264 (new)';
            break;
        case 'amd':
            encoder = 'AMD HW H.264 (AVC)';
            break;
        case 'intel':
            encoder = 'QuickSync H.264';
            break;
        default:
            encoder = 'x264 (Software)';
    }

    // Platform max bitrates
    const platformMaxBitrate = {
        twitch: 6000,
        youtube: 12000,
        kick: 8000,
        facebook: 4000
    };

    // Calculate bitrate (80% of upload, capped at platform max)
    const uploadKbps = uploadSpeed * 1000;
    const recommendedBitrate = Math.floor(uploadKbps * 0.8);
    const maxBitrate = platformMaxBitrate[platform];
    const bitrate = Math.min(recommendedBitrate, maxBitrate);

    // Determine resolution based on bitrate
    let resolution;
    if (bitrate >= 6000) {
        resolution = '1920x1080 (1080p)';
    } else if (bitrate >= 4000) {
        resolution = '1280x720 (720p)';
    } else {
        resolution = '1280x720 (720p)';
    }

    // Determine framerate based on content type
    let framerate;
    switch (contentType) {
        case 'gaming':
            framerate = '60 FPS';
            break;
        case 'chatting':
        case 'irl':
        case 'creative':
            framerate = '30 FPS';
            break;
        default:
            framerate = '60 FPS';
    }

    // Determine preset based on quality priority and encoder
    let preset;
    if (gpu === 'none') {
        // x264 presets
        switch (qualityPriority) {
            case 'performance':
                preset = 'veryfast';
                break;
            case 'balanced':
                preset = 'faster';
                break;
            case 'quality':
                preset = 'fast';
                break;
        }
    } else {
        // Hardware encoder presets
        switch (qualityPriority) {
            case 'performance':
                preset = 'Performance';
                break;
            case 'balanced':
                preset = 'Balanced';
                break;
            case 'quality':
                preset = 'Quality';
                break;
        }
    }

    // Update UI
    document.getElementById('out-encoder').textContent = encoder;
    document.getElementById('out-resolution').textContent = resolution;
    document.getElementById('out-bitrate').textContent = `${bitrate} kbps`;
    document.getElementById('out-framerate').textContent = framerate;
    document.getElementById('out-keyframe').textContent = '2 seconds';
    document.getElementById('out-rate-control').textContent = 'CBR (Constant Bitrate)';
    document.getElementById('out-preset').textContent = preset;
}

function copySettings() {
    const encoder = document.getElementById('out-encoder').textContent;
    const resolution = document.getElementById('out-resolution').textContent;
    const bitrate = document.getElementById('out-bitrate').textContent;
    const framerate = document.getElementById('out-framerate').textContent;
    const keyframe = document.getElementById('out-keyframe').textContent;
    const rateControl = document.getElementById('out-rate-control').textContent;
    const preset = document.getElementById('out-preset').textContent;

    const settingsText = `OBS Recommended Settings:
━━━━━━━━━━━━━━━━━━━━━━
Encoder: ${encoder}
Resolution: ${resolution}
Bitrate: ${bitrate}
Framerate: ${framerate}
Keyframe Interval: ${keyframe}
Rate Control: ${rateControl}
Preset: ${preset}
━━━━━━━━━━━━━━━━━━━━━━
Generated by obsmaskgenerator.com/settings-generator`;

    navigator.clipboard.writeText(settingsText).then(() => {
        const copyBtn = document.getElementById('copy-btn');
        copyBtn.classList.add('copied');
        copyBtn.innerHTML = `
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <path d="M20 6L9 17l-5-5"/>
            </svg>
            Copied!
        `;

        setTimeout(() => {
            copyBtn.classList.remove('copied');
            copyBtn.innerHTML = `
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <rect x="9" y="9" width="13" height="13" rx="2"/>
                    <path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1"/>
                </svg>
                Copy All Settings
            `;
        }, 2000);
    });
}
