document.addEventListener('DOMContentLoaded', () => {
    // Bot Toggle
    const btnBotrix = document.getElementById('btn-botrix');
    const btnStreamlabs = document.getElementById('btn-streamlabs');
    let currentBot = 'botrix'; // default

    // Inputs
    const ctrlFont = document.getElementById('ctrl-font');
    const ctrlFontSize = document.getElementById('ctrl-font-size');
    const ctrlBgColor = document.getElementById('ctrl-bg-color');
    const ctrlBgOpacity = document.getElementById('ctrl-bg-opacity');
    const ctrlUserColor = document.getElementById('ctrl-user-color');
    const ctrlTextColor = document.getElementById('ctrl-text-color');
    const ctrlRadius = document.getElementById('ctrl-radius');
    const ctrlSpacing = document.getElementById('ctrl-spacing');
    
    // Toggles
    const ctrlOutline = document.getElementById('ctrl-outline');
    const ctrlHideAvatar = document.getElementById('ctrl-hide-avatar');
    const ctrlHideBadges = document.getElementById('ctrl-hide-badges');
    
    // Outputs
    const chatPreviewBox = document.getElementById('chat-preview');
    const cssOutput = document.getElementById('css-output');
    const generateBtn = document.getElementById('generate-btn');

    // Bot Selection Logic
    function setBot(botName) {
        currentBot = botName;
        if (botName === 'botrix') {
            btnBotrix.classList.add('active');
            btnStreamlabs.classList.remove('active');
            ctrlHideAvatar.disabled = false;
        } else {
            btnStreamlabs.classList.add('active');
            btnBotrix.classList.remove('active');
            ctrlHideAvatar.disabled = true; // Streamlabs usually doesn't show avatars by default in simple widget
            ctrlHideAvatar.checked = false;
        }
        updatePreview();
    }

    btnBotrix.addEventListener('click', () => setBot('botrix'));
    btnStreamlabs.addEventListener('click', () => setBot('streamlabs'));

    function hexToRgba(hex, opacity) {
        let r = parseInt(hex.slice(1, 3), 16),
            g = parseInt(hex.slice(3, 5), 16),
            b = parseInt(hex.slice(5, 7), 16);
        return `rgba(${r}, ${g}, ${b}, ${opacity / 100})`;
    }

    function updatePreview() {
        const fontFamily = ctrlFont.value;
        const fontSize = ctrlFontSize.value + 'px';
        const bgColor = hexToRgba(ctrlBgColor.value, ctrlBgOpacity.value);
        const userColor = ctrlUserColor.value;
        const textColor = ctrlTextColor.value;
        const radius = ctrlRadius.value + 'px';
        const spacing = ctrlSpacing.value + 'px';
        const outline = ctrlOutline.checked ? '1px 1px 2px black, -1px -1px 2px black, 0px 0px 3px black' : 'none';

        // Apply to preview container wrapper
        chatPreviewBox.style.gap = spacing;

        const chatLines = document.querySelectorAll('.chat-line');
        chatLines.forEach(line => {
            line.style.fontFamily = fontFamily;
            line.style.fontSize = fontSize;
            line.style.backgroundColor = bgColor;
            line.style.borderRadius = radius;
            line.style.textShadow = outline;
        });

        // Avatars
        const avatars = document.querySelectorAll('.chat-avatar');
        avatars.forEach(av => {
            av.style.display = ctrlHideAvatar.checked ? 'none' : 'block';
        });

        // Badges
        const badges = document.querySelectorAll('.chat-badges');
        badges.forEach(bg => {
            bg.style.display = ctrlHideBadges.checked ? 'none' : 'flex';
        });

        // Colors
        const names = document.querySelectorAll('.chat-name');
        names.forEach(name => {
            name.style.color = userColor;
        });

        const msgs = document.querySelectorAll('.chat-message-text');
        msgs.forEach(msg => {
            msg.style.color = textColor;
        });
    }

    function generateCSS() {
        const fontFamily = ctrlFont.value;
        const fontSize = ctrlFontSize.value + 'px';
        const bgColor = hexToRgba(ctrlBgColor.value, ctrlBgOpacity.value);
        const userColor = ctrlUserColor.value;
        const textColor = ctrlTextColor.value;
        const radius = ctrlRadius.value + 'px';
        const spacing = ctrlSpacing.value + 'px';
        const outline = ctrlOutline.checked ? '1px 1px 2px black, -1px -1px 2px black, 0px 0px 3px black' : 'none';
        
        let cssTemplate = `/* Generated by obsmaskgenerator.com */\n`;
        
        if (currentBot === 'botrix') {
            cssTemplate += `
body {
    background: transparent !important;
}

.widget-chat, .chat-message {
    font-family: ${fontFamily} !important;
}

.chat-message {
    font-size: ${fontSize} !important;
    background-color: ${bgColor} !important;
    border-radius: ${radius} !important;
    margin-bottom: ${spacing} !important;
    padding: 8px 12px !important;
    text-shadow: ${outline} !important;
    display: flex !important;
    align-items: flex-start !important;
}

.username {
    color: ${userColor} !important;
    font-weight: bold !important;
}

.message, .text {
    color: ${textColor} !important;
}
`;
            if (ctrlHideAvatar.checked) {
                cssTemplate += `\n.avatar { display: none !important; }\n`;
            }
            if (ctrlHideBadges.checked) {
                cssTemplate += `\n.badges, .badge { display: none !important; }\n`;
            }

        } else if (currentBot === 'streamlabs') {
            cssTemplate += `
body {
    background: transparent !important;
}

#log > div {
    font-family: ${fontFamily} !important;
    font-size: ${fontSize} !important;
    background-color: ${bgColor} !important;
    border-radius: ${radius} !important;
    margin-bottom: ${spacing} !important;
    padding: 8px 12px !important;
    text-shadow: ${outline} !important;
}

.name {
    color: ${userColor} !important;
}

.message {
    color: ${textColor} !important;
}
`;
            if (ctrlHideBadges.checked) {
                cssTemplate += `\n.badges { display: none !important; }\n`;
            }
        }

        cssOutput.value = cssTemplate;
        cssOutput.select();
        document.execCommand('copy');
        generateBtn.innerText = "Copied to Clipboard!";
        generateBtn.style.backgroundColor = "#fff";
        generateBtn.style.color = "#000";
        
        setTimeout(() => { 
            generateBtn.innerText = "Generate & Copy CSS"; 
            generateBtn.style.backgroundColor = "var(--kick-green)";
            generateBtn.style.color = "#000";
        }, 2000);
    }

    // Event listeners
    [ctrlFont, ctrlFontSize, ctrlBgColor, ctrlBgOpacity, ctrlUserColor, ctrlTextColor, ctrlRadius, ctrlSpacing, ctrlOutline, ctrlHideAvatar, ctrlHideBadges].forEach(el => {
        el.addEventListener('input', updatePreview);
    });

    generateBtn.addEventListener('click', generateCSS);

    // Init
    updatePreview();
});
